import "./globals.css";
// import { store } from "@/redux/store";
// import { Provider } from "react-redux";
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Music Listener",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
